name: Deploy Workflow

env:
  aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
  aws_region: us-east-1
  bucket_dev: s3://kse-bucket-dev/
  bucket_prod: s3://kse-bucket-prod/
  cloudfront_id_dev: E25GVWSJOLO9YM
  cloudfront_id_prod: E3VL4ZJ1569SJR

on:
  push:
    branches:
      - dev
      - prod

jobs:
  prejob:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{steps.var_output.outputs.stage}}
      api: ${{steps.var_output.outputs.api}}
      bucket: ${{steps.var_output.outputs.bucket}}
      cloudfront: ${{steps.var_output.outputs.cloudfront}}

    steps:
      - id: var_output
        run: |
          if [ ${{github.ref_name}} == 'prod' ]; then
            echo "stage=prod" >> $GITHUB_OUTPUT
            echo "bucket=${{env.bucket_prod}}" >> $GITHUB_OUTPUT
            echo "cloudfront=${{env.cloudfront_id_prod}}" >> $GITHUB_OUTPUT
          else
            echo "stage=dev" >> $GITHUB_OUTPUT
            echo "bucket=${{env.bucket_dev}}" >> $GITHUB_OUTPUT
            echo "cloudfront=${{env.cloudfront_id_dev}}" >> $GITHUB_OUTPUT
          fi

  deploy-vue:
    runs-on: ubuntu-latest
    needs: prejob

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{env.aws_access_key_id}}
          aws-secret-access-key: ${{env.aws_secret_access_key}}
          aws-region: ${{env.aws_region}}

      - run: |
          echo "start deploy-vue to ${{needs.prejob.outputs.stage}}"
          npm install
          npm run build-${{needs.prejob.outputs.stage}}
          aws s3 rm ${{needs.prejob.outputs.bucket}} --recursive
          aws s3 cp ./dist ${{needs.prejob.outputs.bucket}} --recursive
          aws cloudfront create-invalidation --distribution-id ${{needs.prejob.outputs.cloudfront}} --paths '/*'
        working-directory: ./vue-kse

      - if: failure()
        run: echo "❌ end deploy-vue in failure"

      - if: success()
        run: echo "✅ end deploy-vue in success"
